name: "CI/CD"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_coq:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#coq-artifact